import { createClient } from "@/lib/supabase/server";
import Link from "next/link";
export const revalidate=60;
export const metadata={title:"Nayo Crystal",description:"Nayo Crystal｜生命靈數、缺數水晶、客製生命靈數水晶手環與作品。"};
export default async function Crystal(){
 const supabase=await createClient(); let crystals:any[]=[];let products:any[]=[];
 if(supabase){const [c,p]=await Promise.all([supabase.from("crystals").select("*").order("sort_order"),supabase.from("products").select("*").order("sort_order")]);crystals=c.data||[];products=p.data||[]}
 const nums=Array.from({length:9},(_,i)=>String(i+1));
 return <main className="container page"><div className="eyebrow">NAYO CRYSTAL</div><h1>生命靈數 × 水晶</h1><p className="page-intro">從缺數認識自己，再挑選適合自己的水晶。水晶內容與手環作品都可以從管理後台更新。</p><div className="category-grid" style={{marginTop:35}}>{nums.map(n=><a className="category" href={`#number-${n}`} key={n}><div className="icon">✦</div><strong>生命靈數 {n}</strong><span>查看對應水晶</span></a>)}</div><section className="section"><div className="section-head"><div><div className="section-kicker">CRYSTALS</div><div className="section-title">水晶資料</div></div></div><div className="carousel">{crystals.map((c:any)=><article className="crystal-card" id={`number-${c.life_numbers||""}`} key={c.id}><div className="crystal-art">{c.image_url?<img src={c.image_url} alt={c.name} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:18}}/>:"✦"}</div><div className="crystal-num">生命靈數 {c.life_numbers||""}</div><div className="crystal-name">{c.name}</div><div className="crystal-desc">{c.meaning||""}</div></article>)}</div></section><section className="section" id="bracelets"><div className="section-head"><div><div className="section-kicker">CUSTOM BRACELETS</div><div className="section-title">缺數手環作品</div></div><Link className="more" href="/crystal/buy">購買須知 →</Link></div><div className="carousel">{products.map((p:any)=><article className="crystal-card" key={p.id}><div className="crystal-art">{p.image_url?<img src={p.image_url} alt={p.name} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:18}}/>:"✦"}</div><div className="crystal-num">缺數 {p.missing_numbers||""}</div><div className="crystal-name">{p.name}</div><div className="crystal-desc">{p.description||""}</div>{p.purchase_url&&<a className="promo-button" href={p.purchase_url} target="_blank" rel="noreferrer">購買作品 →</a>}</article>)}</div>{!products.length&&<p style={{color:"#817570"}}>目前還沒有手環作品，登入後台即可新增。</p>}</section></main>
}
